apiVersion: v1
kind: Service
metadata:
  name: booking-ui
  labels:
    app: booking-ui

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http-api
  selector:
    app: booking-ui

